# Generated by Django 2.1.3 on 2019-07-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ChainTest', '0002_order_task'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('order', 'name')},
        ),
    ]
