# Generated by Django 2.1.3 on 2019-07-11 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainTest', '0003_auto_20190711_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Priorytet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='sendDate',
            field=models.DateField(default=datetime.datetime(2019, 9, 1, 0, 0), verbose_name='Data wysyłki'),
            preserve_default=False,
        ),
    ]
